services:
  postgres:
    image: bitnami/postgresql:latest
    environment:
      POSTGRESQL_DATABASE: ignitecall
      POSTGRESQL_USERNAME: docker
      POSTGRESQL_PASSWORD: docker
    ports:
      - "5432:5432"